# Generated by Django 4.0.6 on 2022-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Basico'), (2, 'Intermediário'), (3, 'Administrador')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
