# Generated by Django 4.0.6 on 2022-07-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_colaborador_status'),
        ('empresa', '0002_empresa_status'),
        ('tipo_equipamento', '0002_tipoequipamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_patrimonio', models.CharField(max_length=30, unique=True)),
                ('pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateField()),
                ('situacao', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('especificacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('acesso_remoto', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_id', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_senha', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colaborador.colaborador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_equipamento.tipoequipamento')),
            ],
        ),
    ]
