# Generated by Django 4.0.6 on 2022-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_equipamento_status_alter_equipamento_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
