# Generated by Django 4.0.6 on 2022-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_alter_equipamento_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
