# Generated by Django 4.0.6 on 2022-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
