# Generated by Django 4.0.6 on 2022-07-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_equipamento', '0002_tipoequipamento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoequipamento',
            options={'ordering': ['tipo']},
        ),
    ]
